import { z } from "zod";
import { pg } from "ormer";

// prettier-ignore
export const ZOD_EXAMPLES = [
  () => [z.string(), pg.text()],
  () => [z.string().max(255), pg.varchar({ maxLength: 255 })],
  () => [z.uuid(), pg.uuid()],
  () => [z.number(), pg.float8()],
  () => [z.number().int(), pg.float8()],
  () => [z.float32(), pg.float4()],
  () => [z.float64(), pg.float8()],
  () => [z.int(), pg.int4()],
  () => [z.int().dbPk(), pg.int4({ primaryKey: true, autoIncrement: true })],
  () => [z.bigint(), pg.decimal()],
  () => [z.int32(), pg.int4()],
  () => [z.uint32(), { throws: "PG has no mapping for ZodNumberFormat: uint32" }],
  () => [z.int64(), pg.int8()],
  () => [z.int64().dbPk(), pg.int8({ primaryKey: true, autoIncrement: true })],
  () => [z.uint64(), pg.decimal({ precision: 20, scale: 0 })],
  () => [z.boolean(), pg.boolean()],
  () => [z.date(), pg.timestamptz()],
  () => [z.url(), pg.text()],
  () => [z.email(), pg.text()],
  () => [z.emoji(), pg.text()],
  () => [z.nanoid(), pg.varchar({ maxLength: 21 })],
  () => [z.cuid2(), pg.text()],
  () => [z.ulid(), pg.varchar({ maxLength: 26 })],
  () => [z.xid(), pg.varchar({ maxLength: 20 })],
  () => [z.ksuid(), pg.varchar({ maxLength: 27 })],
  () => [z.base64(), pg.text()],
  () => [z.base64url(), pg.text()],
  () => [z.e164(), pg.text()],
  () => [z.jwt(), pg.text()],
  () => [z.guid(), pg.uuid()],
  () => [z.ipv4(), pg.inet()],
  () => [z.ipv6(), pg.inet()],
  () => [z.mac(), pg.macaddr()],
  () => [z.cidrv4(), pg.cidr()],
  () => [z.cidrv6(), pg.cidr()],

  () => [z.string().nullable(), pg.text({ nullable: true })],
  () => [z.string().optional(), pg.text({ nullable: true })],
  () => [z.string().default("hello"), pg.text({ default: "hello" })],
  () => [z.string().prefault("hello"), pg.text({ default: "hello" })],
  () => [z.string().dbPk(), pg.text({ primaryKey: true })],
  () => [
    z.string().dbFk(
      z.object({ id: z.string() }) .dbTable("users"),
      "id",
    ),
    pg.text({ foreignKeyTable: "users", foreignKeyColumn: "id" }),
  ],
] satisfies Array<() => [z.ZodTypeAny, { type: string } | { throws: string }]>;
